twig:
    default_path: '%kernel.project_dir%/templates'

    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        verseService: '@App\Service\VerseService'



when@test:
    twig:
        strict_variables: true

