vich_uploader:
    db_driver: orm

    mappings:
        program_image:
            uri_prefix: /uploads/programs/
            upload_destination: '%kernel.project_dir%/public/uploads/programs'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true 

        advert_image:
            uri_prefix: /uploads/adverts/
            upload_destination: '%kernel.project_dir%/public/uploads/adverts'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true 

        podcast_image:
            uri_prefix: /uploads/podcasts/
            upload_destination: '%kernel.project_dir%/public/uploads/podcasts'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: false 
        user_image:
            uri_prefix: /uploads/users/
            upload_destination: '%kernel.project_dir%/public/uploads/users'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: false
            delete_on_remove: false 

